/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: (typeof import("antd"))["Button"];
  const Canvas: (typeof import("../src/components/Canvas/index"))["default"];
  const ColorPicker: (typeof import("antd"))["ColorPicker"];
  const Dropdown: (typeof import("antd"))["Dropdown"];
  const Header: (typeof import("../src/components/Header/index"))["default"];
  const InputNumber: (typeof import("antd"))["InputNumber"];
  const Link: (typeof import("@tanstack/react-router"))["Link"];
  const Modal: (typeof import("antd"))["Modal"];
  const Operate: (typeof import("../src/components/Operate/index"))["default"];
  const Outlet: (typeof import("@tanstack/react-router"))["Outlet"];
  const Radio: (typeof import("antd"))["Radio"];
  const Select: (typeof import("antd"))["Select"];
  const Suspense: (typeof import("react"))["Suspense"];
  const Tooltip: (typeof import("antd"))["Tooltip"];
  const classNames: (typeof import("classnames"))["default"];
  const createFileRoute: (typeof import("@tanstack/react-router"))["createFileRoute"];
  const createRef: (typeof import("react"))["createRef"];
  const createRootRoute: (typeof import("@tanstack/react-router"))["createRootRoute"];
  const forwardRef: (typeof import("react"))["forwardRef"];
  const lazy: (typeof import("react"))["lazy"];
  const memo: (typeof import("react"))["memo"];
  const startTransition: (typeof import("react"))["startTransition"];
  const useCallback: (typeof import("react"))["useCallback"];
  const useContext: (typeof import("react"))["useContext"];
  const useDebugValue: (typeof import("react"))["useDebugValue"];
  const useDeferredValue: (typeof import("react"))["useDeferredValue"];
  const useEffect: (typeof import("react"))["useEffect"];
  const useId: (typeof import("react"))["useId"];
  const useImperativeHandle: (typeof import("react"))["useImperativeHandle"];
  const useInsertionEffect: (typeof import("react"))["useInsertionEffect"];
  const useLayoutEffect: (typeof import("react"))["useLayoutEffect"];
  const useMemo: (typeof import("react"))["useMemo"];
  const useReducer: (typeof import("react"))["useReducer"];
  const useRef: (typeof import("react"))["useRef"];
  const useState: (typeof import("react"))["useState"];
  const useSyncExternalStore: (typeof import("react"))["useSyncExternalStore"];
  const useTransition: (typeof import("react"))["useTransition"];
}
