/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BrowserUtils: (typeof import('../src/utils/browser'))['BrowserUtils']
  const Button: (typeof import('antd'))['Button']
  const CSSProperties: (typeof import('react'))['CSSProperties']
  const Canvas: (typeof import('../src/components/Canvas/index'))['default']
  const CanvasUtils: (typeof import('../src/utils/canvas'))['CanvasUtils']
  const Color: (typeof import('../src/components/Operate/components/Color'))['default']
  const ColorIcon: (typeof import('../src/assets/svg/index'))['ColorIcon']
  const ColorPicker: (typeof import('antd'))['ColorPicker']
  const ColorUtils: (typeof import('../src/utils/color'))['ColorUtils']
  const CommonIcon: (typeof import('../src/components/Common/CommonIcon'))['default']
  const Drag: (typeof import('../src/components/Common/Drag'))['default']
  const Dropdown: (typeof import('antd'))['Dropdown']
  const Export: (typeof import('../src/components/Header/components/Export'))['default']
  const Font: (typeof import('../src/components/Operate/components/Font'))['default']
  const Header: (typeof import('../src/components/Header/index'))['default']
  const IconStyle: (typeof import('../src/components/Header/components/IconStyle'))['default']
  const ImgUtils: (typeof import('../src/utils/img'))['ImgUtils']
  const InputNumber: (typeof import('antd'))['InputNumber']
  const Link: (typeof import('@tanstack/react-router'))['Link']
  const LoadingSvg: (typeof import('../src/assets/svg/index'))['LoadingSvg']
  const Material: (typeof import('../src/components/Operate/components/Material'))['default']
  const MenusMap: (typeof import('../src/components/Operate/index'))['MenusMap']
  const Modal: (typeof import('antd'))['Modal']
  const Operate: (typeof import('../src/components/Operate/index'))['default']
  const OperateEnum: (typeof import('../src/components/Operate/components/OperateConent'))['OperateEnum']
  const OperateItem: (typeof import('../src/components/Common/OperateItem'))['default']
  const Outlet: (typeof import('@tanstack/react-router'))['Outlet']
  const Radio: (typeof import('antd'))['Radio']
  const ReactNode: (typeof import('react'))['ReactNode']
  const Select: (typeof import('antd'))['Select']
  const Shape: (typeof import('../src/components/Operate/components/Shape'))['default']
  const ShapeIcon: (typeof import('../src/assets/svg/index'))['ShapeIcon']
  const ShareLinkSvg: (typeof import('../src/assets/svg/index'))['ShareLinkSvg']
  const Suspense: (typeof import('react'))['Suspense']
  const TextEdit: (typeof import('../src/components/Operate/components/TextEdit'))['default']
  const TextIcon: (typeof import('../src/assets/svg/index'))['TextIcon']
  const Tooltip: (typeof import('antd'))['Tooltip']
  const classNames: (typeof import('classnames'))['default']
  const createFileRoute: (typeof import('@tanstack/react-router'))['createFileRoute']
  const createRef: (typeof import('react'))['createRef']
  const createRootRoute: (typeof import('@tanstack/react-router'))['createRootRoute']
  const forwardRef: (typeof import('react'))['forwardRef']
  const immune1: (typeof import('../src/assets/svg/svg9'))['immune1']
  const immune10: (typeof import('../src/assets/svg/svg9'))['immune10']
  const immune11: (typeof import('../src/assets/svg/svg9'))['immune11']
  const immune12: (typeof import('../src/assets/svg/svg9'))['immune12']
  const immune13: (typeof import('../src/assets/svg/svg9'))['immune13']
  const immune14: (typeof import('../src/assets/svg/svg9'))['immune14']
  const immune15: (typeof import('../src/assets/svg/svg9'))['immune15']
  const immune16: (typeof import('../src/assets/svg/svg9'))['immune16']
  const immune2: (typeof import('../src/assets/svg/svg9'))['immune2']
  const immune3: (typeof import('../src/assets/svg/svg9'))['immune3']
  const immune4: (typeof import('../src/assets/svg/svg9'))['immune4']
  const immune5: (typeof import('../src/assets/svg/svg9'))['immune5']
  const immune6: (typeof import('../src/assets/svg/svg9'))['immune6']
  const immune7: (typeof import('../src/assets/svg/svg9'))['immune7']
  const immune8: (typeof import('../src/assets/svg/svg9'))['immune8']
  const immune9: (typeof import('../src/assets/svg/svg9'))['immune9']
  const lazy: (typeof import('react'))['lazy']
  const memo: (typeof import('react'))['memo']
  const startTransition: (typeof import('react'))['startTransition']
  const svg0: (typeof import('../src/assets/svg/svg8'))['svg0']
  const svg1: (typeof import('../src/assets/svg/svg8'))['svg1']
  const svg10: (typeof import('../src/assets/svg/svg8'))['svg10']
  const svg11: (typeof import('../src/assets/svg/svg8'))['svg11']
  const svg2: (typeof import('../src/assets/svg/svg8'))['svg2']
  const svg3: (typeof import('../src/assets/svg/svg8'))['svg3']
  const svg4: (typeof import('../src/assets/svg/svg8'))['svg4']
  const svg5: (typeof import('../src/assets/svg/svg8'))['svg5']
  const svg6: (typeof import('../src/assets/svg/svg8'))['svg6']
  const svg7: (typeof import('../src/assets/svg/svg8'))['svg7']
  const svg8: (typeof import('../src/assets/svg/svg8'))['svg8']
  const svg9: (typeof import('../src/assets/svg/svg8'))['svg9']
  const useCallback: (typeof import('react'))['useCallback']
  const useCanvas: (typeof import('../src/hooks/use-canvas'))['useCanvas']
  const useCanvasStore: (typeof import('../src/store/canvas'))['useCanvasStore']
  const useContext: (typeof import('react'))['useContext']
  const useDebugValue: (typeof import('react'))['useDebugValue']
  const useDeferredValue: (typeof import('react'))['useDeferredValue']
  const useDropImg: (typeof import('../src/hooks/use-drop-img'))['useDropImg']
  const useEffect: (typeof import('react'))['useEffect']
  const useId: (typeof import('react'))['useId']
  const useImperativeHandle: (typeof import('react'))['useImperativeHandle']
  const useInsertionEffect: (typeof import('react'))['useInsertionEffect']
  const useLayoutEffect: (typeof import('react'))['useLayoutEffect']
  const useListenEvent: (typeof import('../src/hooks/use-event'))['useListenEvent']
  const useMemo: (typeof import('react'))['useMemo']
  const useReducer: (typeof import('react'))['useReducer']
  const useRef: (typeof import('react'))['useRef']
  const useState: (typeof import('react'))['useState']
  const useSyncExternalStore: (typeof import('react'))['useSyncExternalStore']
  const useTransition: (typeof import('react'))['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { BrowserUtils } from '../src/utils/browser'
  import('../src/utils/browser')
  // @ts-ignore
  export type { CanvasUtils } from '../src/utils/canvas'
  import('../src/utils/canvas')
  // @ts-ignore
  export type { ColorUtils } from '../src/utils/color'
  import('../src/utils/color')
  // @ts-ignore
  export type { ImgUtils } from '../src/utils/img'
  import('../src/utils/img')
}
